WIDTH_NUM=640
HEIGHT_NUM=640
TRAIN_SPLIT=70
increment=10000
num_div=0
num_classes=1
PREFIX='tiny_yolo-Elements'
darknet_path='/home/steven/darknet'
base_path_OG='/media/steven/Elements/Yolo_Models'
if os.path.exists(base_path_OG)=''/media/steven/Elements/Yolo_Models''
MODEL_PATHS='/media/steven/Elements/Yolo_Models/MODEL_PATHS'
path_JPEGImages=r'/media/steven/Elements/Drone_Videos/Combined_Transporter9_only/JPEGImages'
path_Annotations=r'/media/steven/Elements/Drone_Videos/Combined_Transporter9_only/Annotations'
path_Yolo='/media/steven/Elements/Drone_Videos/Combined_Transporter9_only/YOLO_OBJS'
mp4_video_path=r'/media/steven/Elements/Drone_Videos/DJI_0014.MP4'
root_background_img=r'misc/gradient_green.jpg'
DEFAULT_ENCODING ='utf-8'
XML_EXT ='.xml'
JPG_EXT ='.jpg'
COLOR='red'
root_bg='#000000'
root_fg='#b7f731'
canvas_columnspan=50
canvas_rowspan=50
YOLO_MODEL_PATH=r"/media/steven/Elements/Yolo_Models/tiny_yolo-Elements_w640_h640_d0_c1"
